version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/kodede
hooks:
  BeforeInstall:
    - location: .deploy/scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: .deploy/scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: .deploy/scripts/application_start.sh
      timeout: 300
      runas: ec2-user